### ISSUE TITLE
Separate branch without redux ?

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/youtubetuto-twitter-clone-demo#2]
Hi. I was wondering if you could do a separate branch without using redux  ? The redux code is getting Proper irritating.

**Comment by EQuimper** [comment]
Yes gonna make one :)

**Comment by EQuimper** [comment]
@kaiyes what you think about a other repos for that ?

**Comment by kaiyes** [comment]
@EQuimper  what you mean ? Separate repo ? Fine with me.

**Comment by kaiyes** [comment]
@EQuimper  You can keep this same backend for the next repo you build. Just the front end gotta be different. Even the front end will not be that much Different from this one either, it simply won't have redux. I am starting to like redux a lot. It gives a lot of structure. But I want to see how the code differs between a redux and non redux version

**Comment by EQuimper** [comment]
Yes this is what I plan, sorry last month was crazy gonna restart to grind the code :)
