### ISSUE TITLE
Why fetch the current User ?

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/youtubetuto-twitter-clone-demo#3]
https://github.com/EQuimper/youtubetuto-twitter-clone-demo/blob/master/mobile/src/components/SignupForm.js#L124

I was wondering why you are fetching the current user here ? If you wanted to show the details of the logged in user in the `my Profile` section, could you not query it on that screen/component only ? Or is it because you want to show user avatar in the header which is available throughout the app.

**Comment by EQuimper** [comment]
It's also for the avatar at the top right, I'm recording the video in 5 min and gonna talk about this. The thing is like you say I like to fetch in component but the header need the avatar :s
