### ISSUE TITLE
how to add two separate navigators in redux store ?

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/youtubetuto-twitter-clone-demo#5]
hi. me again 😄  
### Goal : show users login screen if not logged in. As soon as the log in they should be redirected to home screen which is a separate router._

I have auth navigator and main app navigator. Currently I need to restart my app to route a logged in user to homepage. I guess that has to do with the auth navigator state not being stored in redux store. So how do you add two separate navigators in redux store ? 

Anyway, If I want to use authentication router instead of authentication components, where do I plug in with redux ? here ? 

https://github.com/EQuimper/youtubetuto-twitter-clone-demo/blob/master/mobile/src/reducers/navigation.js

or here 
https://github.com/EQuimper/youtubetuto-twitter-clone-demo/blob/master/mobile/src/navigation.js#L233-L236

**Comment by EQuimper** [comment]
Yes good question, for me because of this process where I'm not the most sure I would use `react-native-swiper` and make the transition swipe for the login flow. The thing it's like you say hard to manage the navigation with redux if you have 2 router. Or you can not use the router without redux here ?

**Comment by kaiyes** [comment]
Thanks for answering. I felt the same way as you, its hard maintaining two separate router. I followed your example of component based conditional login flow and it works. two router based login flow is definitely hard and I have stopped trying that.
