### ISSUE TITLE
why add authentication from here if user Reducer has it ? 

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/youtubetuto-twitter-clone-demo#6]
You have user state here 
https://github.com/EQuimper/youtubetuto-twitter-clone-demo/blob/master/mobile/src/reducers/user.js#L3
```
const initialState = {
  token: null,
  isAuthenticated: false,
  info: null,
};
```

then why add it again here ? 
https://github.com/EQuimper/youtubetuto-twitter-clone-demo/blob/master/mobile/src/navigation.js#L235

```
export default withApollo(connect(state => ({
  nav: state.nav,
  isAuthenticated: state.user.isAuthenticated,
}))(AppNavigator));
```

Sorry but I have these questions popping up in my head. 😄  You are a good teacher.

**Comment by EQuimper** [comment]
so here by connect and mapStateToProps the value of the reducer I can have access inside this component the value from it. So here I have access to the value of the reducer and can show a thing if this boolean is true or show other stuff if not. :)
